version: '3'

services:
  backend1:
    build:
      context: ./ProjectFlashback_b
    command: gunicorn ProjectFlashback_b.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  backend2:
    build:
      context: ./ProjectFlashback_b_p2
    command: gunicorn ProjectFlashback_b_p2.wsgi --bind 0.0.0.0:8001 --workers 3 --timeout 120
    ports:
      - "8001:8001"
  frontend:
    build:
      context: ./project-flashback_f
    volumes:
      - react_build:/react/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend1
      - backend2
      - frontend
volumes:
  react_build:
